### ISSUE TITLE
Icon for menu dashboard

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSToolbar-WP#1]
![icon](https://cloud.githubusercontent.com/assets/4999794/7845525/212d8e10-047d-11e5-8a30-fffa9214e612.jpg)

**Comment by billtomczak** [comment]
Can you adjust so that the icon dims when not selected, like the other menu icons?

ost_icon.png was the original file used for that.

**Comment by htmgarcia** [comment]
@billtomczak I added a new icon with two color states

The animation is not the core one but maybe will help to stand out this menu :)

**Comment by billtomczak** [comment]
It certainly will! :)

Okay - good enough. thx
